# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Открыл файл в Google Colab (используйте собственный форк репозитория).
2. Решил задачи.
3. Сохранил результат в репозиторий github в директорию ./les03
4. Создал pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайл работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [1]:
import numpy as np

print("\n1. Массив 10x10:")
arr_10x10 = np.random.random((10, 10))
print(f"Минимум: {arr_10x10.min()}, Максимум: {arr_10x10.max()}")
print(f"Форма массива: {arr_10x10.shape}")


1. Массив 10x10:
Минимум: 0.006357245366742759, Максимум: 0.9896476716766648
Форма массива: (10, 10)


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
import numpy as np

print("\n2. Шахматная доска 8x8:")
chess = np.zeros((8, 8), dtype=int)
chess[1::2, ::2] = 1
chess[::2, 1::2] = 1
print(chess)

3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [5]:
import numpy as np

print("\n3. Смена знака:")
z = np.arange(11)
print(f"До: {z}")
z[(z > 3) & (z < 8)] *= -1
print(f"После: {z}")


3. Смена знака:
До: [ 0  1  2  3  4  5  6  7  8  9 10]
После: [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
import numpy as np

z = np.random.rand(5, 10)
print("Исходная матрица 5x10:")
print(np.round(z, 2))  # Округляем для удобства чтения
print()

# Находим среднее значение для каждой строки
row_means = np.mean(z, axis=1)
print("Средние значения по строкам:")
print(np.round(row_means, 2))
print()

# Вычитаем среднее значение каждой строки из всех элементов этой строки
z_normalized = z - row_means.reshape(-1, 1)

print("Матрица после вычитания средних значений:")
print(np.round(z_normalized, 2))
print()

# Проверяем, что средние значения новых строк равны 0
new_means = np.mean(z_normalized, axis=1)
print("Средние значения после нормализации (должны быть близки к 0):")
print(np.round(new_means, 2))

Исходная матрица 5x10:
[[0.95 0.59 0.42 0.59 0.78 0.35 0.87 0.54 0.69 0.19]
 [0.85 0.69 0.26 0.04 0.52 0.6  0.31 0.71 0.85 0.2 ]
 [0.52 0.66 0.13 0.43 0.21 0.12 0.18 0.65 0.56 0.47]
 [1.   0.68 0.16 0.55 0.62 0.43 0.96 0.59 0.39 0.72]
 [0.05 0.37 0.92 0.87 0.76 0.72 0.8  0.37 0.86 0.74]]

Средние значения по строкам:
[0.6  0.5  0.39 0.61 0.65]

Матрица после вычитания средних значений:
[[ 0.35 -0.01 -0.18 -0.    0.18 -0.24  0.27 -0.06  0.09 -0.41]
 [ 0.35  0.19 -0.24 -0.47  0.02  0.09 -0.2   0.21  0.35 -0.31]
 [ 0.13  0.27 -0.26  0.04 -0.18 -0.28 -0.22  0.26  0.17  0.07]
 [ 0.39  0.07 -0.45 -0.06  0.01 -0.18  0.35 -0.02 -0.22  0.11]
 [-0.6  -0.28  0.28  0.22  0.12  0.07  0.15 -0.28  0.22  0.09]]

Средние значения после нормализации (должны быть близки к 0):
[-0. -0.  0.  0. -0.]


5. Поменяйте 1 и 2 строки матрицы

In [3]:
import numpy as np

z = np.arange(25).reshape(5,5)
print(f"Исходная матрица:\n{z}")
z[[0, 1]] = z[[1, 0]]
print(f"После замены строк:\n{z}")

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
После замены строк:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [2]:
import numpy as np

z = np.random.random((10,2))
print(f"Декартовы координаты:\n{z}")
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar_coords = np.column_stack((r, theta))
print(f"Полярные координаты:\n{polar_coords}")

Декартовы координаты:
[[0.28664315 0.48924395]
 [0.38476312 0.22850153]
 [0.7156939  0.29830289]
 [0.32829705 0.49990296]
 [0.96993973 0.6247406 ]
 [0.16952073 0.52756795]
 [0.27145629 0.44423154]
 [0.70277171 0.29199064]
 [0.34825083 0.5717768 ]
 [0.17146785 0.58137315]]
Полярные координаты:
[[0.56703081 1.04081642]
 [0.44749928 0.5359043 ]
 [0.77537241 0.39490671]
 [0.59806514 0.98971044]
 [1.15372609 0.57221817]
 [0.55413466 1.25989199]
 [0.52060558 1.02227731]
 [0.76101682 0.39378327]
 [0.6694829  1.023736  ]
 [0.60613197 1.28399188]]


7. Заменить максимальный элемент массива на ноль

In [1]:
import numpy as np
z = np.random.random(10)
print(f"Исходный массив: {z}")
z[z.argmax()] = 0
print(f"После замены: {z}")

Исходный массив: [0.28925739 0.82034575 0.62204519 0.78950834 0.17306449 0.0434449
 0.32664223 0.1651916  0.597615   0.11684291]
После замены: [0.28925739 0.         0.62204519 0.78950834 0.17306449 0.0434449
 0.32664223 0.1651916  0.597615   0.11684291]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
import numpy as np
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
print(f"Исходный массив: {z}")
print(f"Индексы: {i}")
np.add.at(z, i, 1)
print(f"После добавления: {z}")

Исходный массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Индексы: [5 7 9 6 3 7 3 6 7 4 2 6 7 5 0 7 7 7 4 1]
После добавления: [2. 2. 2. 3. 3. 3. 4. 8. 1. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [2]:
import numpy as np

z = np.array([1,2,3,4,5])
result = np.zeros(len(z) + (len(z)-1)*3)
result[::4] = z
print(f"Исходный вектор: {z}")
print(f"Результат: {result}")

Исходный вектор: [1 2 3 4 5]
Результат: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [5]:
import numpy as np

z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
idx = (np.abs(z - v)).argmin()
nearest = z[idx]
print(f"Массив: 0-99, Искомое значение: {v:.2f}")
print(f"Ближайшее число: {nearest}")

Массив: 0-99, Искомое значение: 26.67
Ближайшее число: 27


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

In [ ]:
import numpy as np

# 1. Целочисленный массив
arr1 = np.array([1, 4, 2, 5, 3])
print("1.", arr1.dtype)  # dtype('int64')

# 2. Вещественный массив (из-за 1.)
arr2 = np.array([1., 4, 2, 5, 3])
print("2.", arr2.dtype)  # dtype('float64')

# 3. Вещественный с повышенной точностью
arr3 = np.array([1, 4, 2, 5, 3], dtype='float64')
print("3.", arr3.dtype)  # dtype('float64')

# 4. Комплексные числа
arr4 = np.array([1., 4, 2, 5, 3], dtype='complex128')
print("4.", arr4.dtype)  # dtype('complex128')

# 5. Явное указание float64
arr5 = np.array([1, 4, 2, 5, 3], dtype='float64')
print("5.", arr5.dtype)  # dtype('float64')

# 6. ОШИБКА - нет кавычек
try:
    arr6 = np.array([1, 4, 2, 5, 3], dtype=int64)
    print("6.", arr6.dtype)
except NameError as e:
    print("6. Ошибка:", e)  # NameError: name 'int64' is not defined

# 7. Булев тип
arr7 = np.array([1, 4, 2, 5, 3], dtype='bool')
print("7.", arr7.dtype)  # dtype('bool')
print("   Значения:", arr7)  # [True True True True True]

# 8. Строковый тип
arr8 = np.array([1, 4, 2, 5, 3], dtype='str')
print("8.", arr8.dtype)  # dtype('<U1')

# 9. Автоматическое приведение к строке
arr9 = np.array([1, 4, 2, 5, '3'])
print("9.", arr9.dtype)  # dtype('<U1')

# 10. Комплексные числа
arr10 = np.array([1, -4, 2, 0, 1j])
print("10.", arr10.dtype)  # dtype('complex128')

1. int64
2. float64
3. float64
4. complex128
5. float64
6. int64
7. bool
   Значения: [ True  True  True  True  True]
8. <U1
9. <U21
10. complex128


**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

In [17]:
import numpy as np

# 1. Конкатенация строк
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'  # '41'

# 2. Логическое ИЛИ
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]  # -4

# 3. Логическое И
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]  # False

# 4. Преобразование bool в int
np.array([1, -4, 2, 0, True], dtype='int64')[-1]  # 1

# 5. ОШИБКА - нельзя комплексное в int
# np.array([1, -4, 2, 0, 1j], dtype='int64')[1]  # TypeError

# 6. Комплексное число в строку
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]  # '1j'

# 7. Повторение строки
np.array([1, 4, 2, 5, '3'])[-1] * 3  # '333'

'333'

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5)) 
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



In [18]:
# 1. Массив из единиц
np.ones((3, 5), dtype=float)  # 3x5 массив с 1.0

# 2. Заполнение константой
np.full((3, 5), 3.14)  # 3x5 массив с 3.14

# 3. Линейное пространство
np.linspace(0, 1, 5)  # [0., 0.25, 0.5, 0.75, 1.]

# 4. Диагональная матрица
np.diag((1,3,5))  # [[1,0,0], [0,3,0], [0,0,5]]

# 5. ОШИБКА - нет такой функции
# np.smile((1,3,5))  # AttributeError

# 6. Случайные числа
np.random.random((3, 3))  # 3x3 массив случайных чисел [0,1)

# 7. Единичная матрица
np.eye(3)  # [[1,0,0], [0,1,0], [0,0,1]]

# 8. Неинициализированный массив
np.empty(3)  # 3 элемента со случайными значениями

array([4.9e-324, 1.5e-323, 2.5e-323])

**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

In [19]:
X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])

X[0,0]           # 3
X[-1,-1]         # 7
X[0:1,-1]        # array([4])
X[0:2,-1]        # array([4, 8])
X[0:2,0:2]       # array([[3, 5], [7, 6]])
X[1,1:3]         # array([6, 8])
X[1,:]           # array([7, 6, 8, 8])
X[:,:]           # Весь исходный массив
X[:]             # Весь исходный массив
X[::2,::2]       # array([[3, 2], [1, 7]])
X[0:3:2,0:3:2]   # array([[3, 2], [1, 7]])
X[::-1,::-1]     # Массив, перевернутый по обеим осям

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])  
np.split(grid, [2], axis=1) 
```


In [20]:
import numpy as np

grid = np.arange(16).reshape((4, 4))
print("Исходный массив:")
print(grid)
print()

# Разделение по строкам (ось 0)
result1 = np.split(grid, [2])
print("1. np.split(grid, [2]) - разделение по строкам:")
print("Первая часть (строки 0-1):")
print(result1[0])
print("Вторая часть (строки 2-3):")
print(result1[1])
print()

# Разделение по столбцам (ось 1)
result2 = np.split(grid, [2], axis=1)
print("2. np.split(grid, [2], axis=1) - разделение по столбцам:")
print("Первая часть (столбцы 0-1):")
print(result2[0])
print("Вторая часть (столбцы 2-3):")
print(result2[1])

Исходный массив:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

1. np.split(grid, [2]) - разделение по строкам:
Первая часть (строки 0-1):
[[0 1 2 3]
 [4 5 6 7]]
Вторая часть (строки 2-3):
[[ 8  9 10 11]
 [12 13 14 15]]

2. np.split(grid, [2], axis=1) - разделение по столбцам:
Первая часть (столбцы 0-1):
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Вторая часть (столбцы 2-3):
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]   
    np.array([1, 2, 3]) + np.array([3, 2, 1])  
```

In [21]:
[1, 2, 3] + [3, 2, 1]  # Конкатенация: [1, 2, 3, 3, 2, 1]

[1, 2, 3, 3, 2, 1]

In [22]:
np.array([1, 2, 3]) + np.array([3, 2, 1])  # Поэлементное сложение: [4, 4, 4]

array([4, 4, 4])

**7**. Как в CodeLab измерить время выполнения кода?

- **%time** — выполняет выражение один раз и выводит затраченное время.

In [23]:
%time sum(range(1000000))

CPU times: total: 15.6 ms
Wall time: 8.5 ms


499999500000

- **%timeit** — выполняет выражение много раз (подбирает автоматически) и выводит среднее время выполнения. Лучше подходит для точного измерения скорости небольших фрагментов кода.

In [24]:
%timeit sum(range(1000000))

7.79 ms ± 47.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

In [25]:
X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])
print("np.sum(X) -> 64 (сумма всех элементов)")
print("np.sum(X, axis=1) -> [14, 29, 21] (суммы по строкам)")
print("np.sum(X, axis=0) -> [11, 17, 17, 19] (суммы по столбцам)")
print("np.sum(X, axis=2) -> Ошибка (только 2 оси)")
print("np.sum(X, 1) -> [14, 29, 21] (то же что axis=1)")
print("sum(X) -> [11, 17, 17, 19] (суммы по столбцам)")
print("sum(X,1) -> Ошибка (для списков другой синтаксис)")

np.sum(X) -> 64 (сумма всех элементов)
np.sum(X, axis=1) -> [14, 29, 21] (суммы по строкам)
np.sum(X, axis=0) -> [11, 17, 17, 19] (суммы по столбцам)
np.sum(X, axis=2) -> Ошибка (только 2 оси)
np.sum(X, 1) -> [14, 29, 21] (то же что axis=1)
sum(X) -> [11, 17, 17, 19] (суммы по столбцам)
sum(X,1) -> Ошибка (для списков другой синтаксис)


**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

In [26]:
X = np.array([1,2,3,4])

X > 3           # array([False, False, False,  True])
X < 3           # array([ True,  True, False, False])
X[X < 3]        # array([1, 2])
X[X > 3]        # array([4])
X[X != 3]       # array([1, 2, 4])

array([1, 2, 4])

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

- **Быстродействие** - операции выполняются в 10-100 раз быстрее
- **Векторизация** - операции над массивами без явных циклов  
- **Эффективное использование памяти** - меньше накладных расходов
- **Большой набор математических функций** - линейная алгебра, статистика, Фурье-анализ
- **Интеграция с научными библиотеками** - SciPy, Pandas, Matplotlib
- **Многомерные массивы** - удобная работа с матрицами и тензорами
- **Удобный синтаксис** - лаконичные операции с массивами
- **Трансляция (broadcasting)** - автоматическое расширение массивов

**Обусловлено:**

- **Хранение в непрерывных блоках памяти** - лучше использование кэша процессора
- **Использование оптимизированных низкоуровневых библиотек** (BLAS, LAPACK)
- **Отсутствие проверки типов во время выполнения** - типы известны заранее
- **Эффективные алгоритмы** - написанные на C/Fortran
- **Векторизация процессора** - использование SIMD инструкций
- **Гомогенность данных** - все элементы одного типа
- **Статическая типизация** - типы фиксированы при создании массива